version: "3"

services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - 45000:3306/tcp
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql8.cnf:/etc/mysql/conf.d/recipedb.cnf"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: '%'

  auth:
    build: ops/develop
    volumes:
      - .:/recipes:delegated
      - gopkg:/go/pkg/mod
    ports:
      - "9000:80/tcp"
      - "9100:40000/tcp"
    cap_add:
      - SYS_PTRACE
    command: ops/develop/startup.sh serve auth
  
  cookbook:
    build: ops/develop
    volumes:
      - .:/recipes:delegated
      - gopkg:/go/pkg/mod
    ports:
      - "8000:80/tcp"
      - "8100:40000/tcp"
    cap_add:
      - SYS_PTRACE
    command: ops/develop/startup.sh serve cookbook

  recipes:
    image: recipes:latest
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
    
      

volumes:
  mysql-data: {}
  gopkg:
