// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/jonDufty/recipes/cookbook/rpc/cookbookpb"
)

type RecipeInput struct {
	Title        string                    `json:"title"`
	Description  string                    `json:"description"`
	Ingredients  []*cookbookpb.Ingredient  `json:"ingredients"`
	Instructions []*cookbookpb.Instruction `json:"instructions"`
}
