on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  # Linting
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        go-version: '1.17'
    - name: install golint
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: run golint
      run: golint .
    - name: run tests
      run: echo "Run tests here..."
    
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build me a docker image!!"

  


