on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -D gosimple

    - name: run tests
      run: echo "Run tests here..."
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        go-version: '1.17'
    - run: go test ./...
  
  # Build
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build me a docker image!!"

  


