on: 
  push:
  pull_request:
    branches:
      - master

jobs:
  # Linting
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        go-version: '1.17'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: run tests
      run: echo "Run tests here..."
    
  # Build
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: echo "Build me a docker image!!"

  


